[package]
name = "Foundry"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = "0.30"
ash = "0.38"
ash-window = "0.13.0"
nalgebra-glm = "0.19"
raw-window-handle = "0.6" 

[dependencies.vulkan-headers]
version = "0.1.1+1.4.336"
features = ["beta_extensions"]

